### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by hieronymousch** [pwFoo/rss-to-activitypub-docker#1]
Thanks for your docker, I wanted to give it a try but installation fails. I'm unable to compile the docker.

Error message: make: Leaving directory '/app/node_modules/generate-rsa-keypair/build'
make: *** [generate-rsa-keypair.target.mk:111: Release/obj.target/generate-rsa-keypair/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 4.15.0-112-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /app/node_modules/generate-rsa-keypair
gyp ERR! node -v v14.9.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm WARN bot-node@1.0.0 No repository field.

**Comment by hieronymousch** [comment]
This problem is caused by rss-bot script, not by your docker...
